encyclopedia/urls.py
from unicodedata import name
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("create", views.create, name="create"),
    path("wiki/<str:title>", views.entry, name="entry"),
    path("wiki/<str:title>/edit", views.edit, name="edit"),
    path("random", views.random, name="random"),
    path("search", views.search, name="search"),
    path("<str:title>", views.error, name="error"),
]

urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/forms.py
from django import forms

from encyclopedia import util

class NewEntryForm(forms.Form):
    title = forms.CharField(
        label="",
        max_length=50,
        widget=forms.TextInput(attrs={'class': "form-control text"})
    )
    entry = forms.CharField(
        label="",
        widget=forms.Textarea(attrs={'class': "form-control text textarea"})
    )

    def clean_title(self):
        title = self.cleaned_data.get('title')

        if util.get_entry(title) != None:
            raise forms.ValidationError("The page \"" + title + "\" already exists")

        return title

class EditEntryForm(forms.Form):
    content = forms.CharField(
        label="",
        widget=forms.Textarea(attrs={'class': "form-control text textarea"})
    )

class SearchForm(forms.Form):
    title = forms.CharField(
        label="",
        max_length=50,
        widget=forms.TextInput(attrs={
            'class': "search form-control form-control-sm",
            'type': "text",
            'name': "q",
            'placeholder': "Search Encyclopedia"
        })
    )

encyclopedia/views.py
from django.shortcuts import redirect, render
from django.urls import reverse
from markdown2 import Markdown

from . import util
from . import forms

def render_helper(request, link, context={}):
    if context.get('search') == None:
        context['search'] = forms.SearchForm()

    context['entries'] = util.list_entries()
    
    return render(request, link, context)

def index(request):
    return render_helper(request, "encyclopedia/index.html")

def error(request, title):
    return render_helper(request, "encyclopedia/error.html", {'title': title})

def entry(request, title):
    entry = util.get_entry(title)

    if entry != None:
        markdowner = Markdown()

        return render_helper(request, "encyclopedia/entry.html", {
            'title': title,
            'entry': markdowner.convert(entry)
        })

    return error(request, title)

def create(request):
    if request.method == 'POST':
        form = forms.NewEntryForm(request.POST)

        if form.is_valid():
            title = form.cleaned_data['title']
            content = form.cleaned_data['entry']
            util.save_entry(title, content)

            return redirect(reverse('entry', args=[title]))
    else:
        form = forms.NewEntryForm()

    return render_helper(request, "encyclopedia/create.html", {'form': form})

def edit(request, title):
    if request.method == 'POST':
        form = forms.EditEntryForm(request.POST)

        if form.is_valid():
            content = form.cleaned_data['content']
            util.save_entry(title, content)

            return redirect(reverse('entry', args=[title]))

    content = util.get_entry(title)
    if content == None: error(request, title)

    return render_helper(request, "encyclopedia/edit.html", {
        'title': title,
        'form': forms.EditEntryForm(initial={'content': content})
    })

def random(request):
    title = util.random_entry()
    return redirect(reverse('entry', args=[title]))

def search(request):
    context = {
        'title': None,
        'search': None,
        'matches': None
    }

    if request.method == 'POST':
        form = forms.SearchForm(request.POST)

        if form.is_valid():
            title = form.cleaned_data['title']
            context.update({'title': title})
            context.update({'search': forms.SearchForm(initial={'title': title})})

            if util.get_entry(title) != None:
                return redirect(reverse('entry', args=[title]))
            
            matches = util.matching_entries(title)
            context.update({'matches': matches})
    
    return render_helper(request, "encyclopedia/search.html", context)

encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New Page - Encyclopedia
{% endblock %}

{% block body %}
    <h1>Create New Page</h1>

    <form action="{% url "create" %}" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_title" class="form-label">Page Title:</label>
            {{ form.title }}
            {% for error in form.title.errors %}
                <div id="contentHelp" class="form-text text-danger">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-exclamation-circle-fill" viewBox="0 0 16 16">
                        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8 4a.905.905 0 0 0-.9.995l.35 3.507a.552.552 0 0 0 1.1 0l.35-3.507A.905.905 0 0 0 8 4zm.002 6a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
                    </svg>
                    {{ error }}
                </div>
            {% endfor %}
        </div>
        <div class="mb-3">
            <label for="id_entry" class="form-label">Page Content:</label>
            {{ form.entry }}
            <div id="contentHelp" class="form-text">
                Please note that this wiki uses <a href="https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax">Github Markdown</a> to style its pages, which is then converted to HTML when the page is visited.
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }} - Edit - Encyclopedia
{% endblock %}

{% block body %}
    <h1>{{ title }} - Edit Page</h1>

    <form action="{% url 'edit' title=title %}" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_content" class="form-label">Page Content:</label>
            {{ form.content }}
            <div id="contentHelp" class="form-text">
                Please note that this wiki uses <a href="https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax">Github Markdown</a> to style its pages, which is then converted to HTML when the page is visited.
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }} - Encyclopedia
{% endblock %}

{% block body %}
    {{ entry|safe }}

    <div class="edit">
        <a class="btn btn-primary btn-sm" href="{% url 'edit' title=title %}">Edit Page</a>
    </div>
{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Page Not Found: {{ title }} - Encyclopedia
{% endblock %}

{% block body %}
    <div class="alert alert-danger d-flex align-items-center" role="alert">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
            <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
        </svg>
        <div>
            Error: <b>{{ title }}</b> does not exist
        </div>
    </div>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <div class="list-group list-group-flush">
        {% for entry in entries %}
            <a href="{% url 'entry' title=entry %}" class="list-group-item list-group-item-action d-flex">
                <div class="entry-icon">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-circle-fill" viewBox="0 0 16 16">
                        <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z"/>
                    </svg>
                </div>
                {{ entry }}
            </a>
        {% endfor %}
    </div>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                {% if request.path != '/search' %}
                    <div class="section">
                        <form action="{% url 'search' %}" method="post">
                            {% csrf_token %}
                            {{ search }}
                        </form>
                    </div>
                {% endif %}
                <nav class="nav d-grid gap-2 section">
                    <a href="{% url 'index' %}" class="btn btn-outline-secondary btn-sm">Home</a>
                    <a href="{% url 'create' %}" class="btn btn-outline-secondary btn-sm">Create New Page</a>
                    <a href="{% url 'random' %}" class="btn btn-outline-secondary btn-sm">Random Page</a>
                </nav>
                {% if request.path != '/' %}
                    <nav class="nav d-grid gap-2 section">
                        <div>All Pages</div>
                
                        {% for entry in entries %}
                            <a href="{% url 'entry' title=entry %}" class="btn btn-outline-secondary btn-sm">{{ entry }}</a>
                        {% endfor %}
                    </nav>
                {% endif %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search - Encyclopedia
{% endblock %}

{% block body %}
    <h1>Search</h1>

    <form action="{% url 'search' %}" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_title" class="form-label">Page Title:</label>
            {{ search }}
            {% if title != None %}
                <div id="contentHelp" class="form-text text-danger">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-exclamation-circle-fill" viewBox="0 0 16 16">
                        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8 4a.905.905 0 0 0-.9.995l.35 3.507a.552.552 0 0 0 1.1 0l.35-3.507A.905.905 0 0 0 8 4zm.002 6a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
                    </svg>
                    {{ title }} does not exist
                </div>
            {% endif %}
        </div>
        {% if matches %}
            <div class="mb-3">
                <label class="form-label">Similar Results:</label>
                <div class="list-group list-group-flush list-group-small">
                    {% for entry in matches %}
                        <a href="{% url 'entry' title=entry %}" class="list-group-item list-group-item-action d-flex">
                            <div class="entry-icon">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-circle-fill" viewBox="0 0 16 16">
                                    <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z"/>
                                </svg>
                            </div>
                            {{ entry }}
                        </a>
                    {% endfor %}
                </div>
            </div>
        {% endif %}
        <button type="submit" class="btn btn-primary">Search</button>
    </form>
{% endblock %}